#config_version=5

mode:
  start_events:
    - cmd_start_mode_placeholder_e
  stop_events:
    - cmd_stop_mode_placeholder_e
  priority: 10000

timers:
  placeholder_e_timer:
    start_value: 0
    end_value: 5
    tick_interval: 1s
    direction: up
    start_running: True

slides:
  placeholder_e_slide:
    widgets:
      - type: text
        text: PLACEHOLDER E
        style: small

slide_player:
  mode_placeholder_e_started:
    placeholder_e_slide:
      priority: 300
      expire: 5

event_player:
  mode_placeholder_e_started: cmd_release_all_bh_mode_van
  timer_placeholder_e_timer_complete: cmd_stop_placeholder_e_mode
