#config_version=5

mode:
  start_events:
    - cmd_start_mode_sally
  stop_events:
    - cmd_stop_mode_sally
  priority: 10000

##################################################
# Events
##################################################

event_player:
  mode_sally_started:
    cmd_mode_intro_started:
    cmd_disable_bh_mode_van:
    cmd_sally_set_state_starting:
    cmd_sally_reset_shot_accrual:
    cmd_sally_reset_variables:
    cmd_sally_start_intro_slide:
    cmd_sally_start_intro_slide_sound:

  timer_sally_timer_1_complete:
    cmd_stop_sally_mode:

  timer_sally_timer_2_complete:
    cmd_stop_sally_mode:

  slide_sally_intro_slide_removed:
    cmd_sally_after_intro_complete:

  cmd_sally_after_intro_complete:
    cmd_mode_intro_complete:
    cmd_sally_set_state_pop_bumpers:
    cmd_play_sally_bg_music_phase_1:
    cmd_eject_van_vuk_with_audio:
    cmd_sally_refresh_lights:
    cmd_sally_play_pop_bumper_slide:

  player_v_sally_pop_bumper_counter{current_player.v_sally_pop_bumper_counter<=0}:
    cmd_sally_start_shot_phase:

  cmd_sally_start_shot_phase:
    cmd_sally_set_state_shots:
    cmd_stop_sally_bg_music_phase_1:
    cmd_play_sally_bg_music_phase_2:
    cmd_sally_show_eyes_set_var:
    cmd_stop_sally_timer_1:
    cmd_start_sally_timer_2:
    cmd_sally_refresh_lights:
    cmd_sally_remove_pop_bumper_slide:
    cmd_sally_add_shots_slide:

  logicblock_sally_shot_accrual_complete:
    cmd_sally_start_final_phase:

  cmd_sally_start_final_phase:
    cmd_add_timer_2_time:
    cmd_sally_set_state_final:
    cmd_sally_refresh_lights:
    cmd_sally_add_final_slide:
    # this gets removed in mode_manager - any changes here have to happen there
    cmd_custom_magna_vuk_queue_event:
      post: cmd_sally_final_shot
      wait_for: slide_sally_complete_slide_removed
      priority: 1000
      mode: sally
      coil_direction: left

  cmd_sally_final_shot:
    # memorabilia
    cmd_sally_score_escape:
    cmd_sally_add_complete_slide:
    cmd_sally_play_complete_audio:

  slide_sally_complete_slide_removed:
    cmd_stop_sally_mode:

  #### Lights ####

  cmd_sally_refresh_lights:
    cmd_sally_clear_playfield_lights:
    cmd_sally_turn_on_playfield_lights:

  cmd_sally_turn_on_playfield_lights{current_player.v_sally_state=="pop_bumpers"}:
    cmd_sally_flash_pop_bumpers:

  cmd_sally_turn_on_playfield_lights.1{current_player.v_sally_state=="shots" and current_player.v_sally_left_orbit_hit!=1}:
    cmd_sally_light_left_orbit:

  cmd_sally_turn_on_playfield_lights.3{current_player.v_sally_state=="shots" and current_player.v_sally_left_ramp_hit!=1}:
    cmd_sally_light_basket_ramp:

  cmd_sally_turn_on_playfield_lights.5{current_player.v_sally_state=="shots" and current_player.v_sally_right_ramp_hit!=1}:
    cmd_sally_light_right_ramp:

  cmd_sally_turn_on_playfield_lights.6{current_player.v_sally_state=="shots" and current_player.v_sally_right_orbit_hit!=1}:
    cmd_sally_light_right_orbit:

  cmd_sally_turn_on_playfield_lights.4{current_player.v_sally_state=="final"}:
    cmd_sally_light_slaughter_house:

  #### Switch Hits ###

  top_turbo_bumper_hit{current_player.v_sally_state=="pop_bumpers"}:
    - cmd_sally_score_pop_bumper
    - sally_pop_bumper_hit
    - cmd_sally_clear_pop_bumper_sound
    - cmd_sally_pop_bumper_sound_1

  left_turbo_bumper_hit{current_player.v_sally_state=="pop_bumpers"}:
    - cmd_sally_score_pop_bumper
    - sally_pop_bumper_hit
    - cmd_sally_clear_pop_bumper_sound
    - cmd_sally_pop_bumper_sound_2

  right_turbo_bumper_hit{current_player.v_sally_state=="pop_bumpers"}:
    - cmd_sally_score_pop_bumper
    - sally_pop_bumper_hit
    - cmd_sally_clear_pop_bumper_sound
    - cmd_sally_pop_bumper_sound_3

  sally_pop_bumper_hit{current_player.v_sally_pop_bumper_timer_running==0}:
    - cmd_sally_start_pop_bumper_timer 

  sally_pop_bumper_hit{current_player.v_sally_pop_bumper_timer_running==1}:
    - cmd_sally_reset_pop_bumper_timer 

  left_orbit_hit{current_player.v_sally_state=="shots" and current_player.v_sally_left_orbit_hit!=1}:
    - cmd_sally_score_wiggle
    - sally_shot_hit
    - cmd_set_sally_left_orbit_hit
    - cmd_sally_refresh_lights
    - cmd_sally_left_orbit_hit

  left_ramp_hit{current_player.v_sally_state=="shots" and current_player.v_sally_left_ramp_hit!=1}:
    - cmd_sally_score_wiggle
    - sally_shot_hit
    - cmd_set_sally_left_ramp_hit
    - cmd_sally_refresh_lights
    - cmd_sally_left_ramp_hit

  right_ramp_hit{current_player.v_sally_state=="shots" and current_player.v_sally_right_ramp_hit!=1}:
    - cmd_sally_score_hand_free
    - sally_shot_hit
    - cmd_set_sally_right_ramp_hit
    - cmd_sally_refresh_lights
    - cmd_sally_right_ramp_hit

  right_orbit_hit{current_player.v_sally_state=="shots" and current_player.v_sally_right_orbit_hit!=1}:
    - cmd_sally_score_hand_free
    - sally_shot_hit
    - cmd_set_sally_right_orbit_hit
    - cmd_sally_refresh_lights
    - cmd_sally_right_orbit_hit

  player_v_sally_shot_counter{value==1}:
    cmd_play_sally_escape_1:

  player_v_sally_shot_counter{value==2}:
    cmd_play_sally_escape_2:

  player_v_sally_shot_counter{value==3}:
    cmd_play_sally_escape_3:

  player_v_sally_shot_counter{value==4}:
    cmd_play_sally_escape_4:

  #### Shows ####

  timer_sally_timer_pop_bumper_started:
    cmd_sally_show_eyes_set_var:

  timer_sally_timer_pop_bumper_complete:
    cmd_sally_remove_eyes_set_var:

  cmd_sally_show_eyes_set_var:
    cmd_sally_set_pop_bumper_timer_running_1:
    cmd_sally_show_eyes_slide:

  cmd_sally_remove_eyes_set_var:
    cmd_sally_set_pop_bumper_timer_running_0:
    cmd_sally_remove_eyes_slide:

##################################################
# Logicblocks
##################################################

accruals:
  sally_shot_accrual:
    events:
      - cmd_sally_left_orbit_hit
      - cmd_sally_left_ramp_hit
      - cmd_sally_right_ramp_hit
      - cmd_sally_right_orbit_hit
    reset_events:
      cmd_sally_reset_shot_accrual:
    reset_on_complete: True
    disable_on_complete: True

##################################################
# Timers
##################################################

timers:
  sally_timer_1:
    start_value: 0
    end_value: 60
    tick_interval: 1s
    direction: up
    start_running: True
    control_events:
      - action: stop
        event: cmd_stop_sally_timer_1

  sally_timer_2:
    start_value: 0
    end_value: 60
    tick_interval: 1s
    direction: up
    start_running: False
    control_events:
      - action: stop
        event: cmd_stop_sally_timer_2
      - action: start
        event: cmd_start_sally_timer_2
      - action: add
        event: cmd_add_timer_2_time
        value: 10

  sally_timer_pop_bumper:
    start_value: 0
    end_value: 2
    tick_interval: 1s
    direction: up
    start_running: False
    control_events:
      - action: restart
        event: cmd_sally_start_pop_bumper_timer
      - action: reset
        event: cmd_sally_reset_pop_bumper_timer

##################################################
# Variables
##################################################

variable_player:
  cmd_sally_set_state_starting:
    v_sally_state:
      action: set
      string: "starting"

  cmd_sally_set_state_pop_bumpers:
    v_sally_state:
      action: set
      string: "pop_bumpers"

  cmd_sally_set_state_shots:
    v_sally_state:
      action: set
      string: "shots"

  cmd_sally_set_state_final:
    v_sally_state:
      action: set
      string: "final"

  cmd_sally_reset_variables:
    # remember to set the starting_count
    v_sally_pop_bumper_counter:
      action: set
      int: 20

    v_sally_left_orbit_hit:
      action: set
      int: 0

    v_sally_left_ramp_hit:
      action: set
      int: 0

    v_sally_right_ramp_hit:
      action: set
      int: 0

    v_sally_right_orbit_hit:
      action: set
      int: 0

    v_sally_shot_counter:
      action: set
      int: 0

    v_sally_pop_bumper_timer_running:
      action: set
      int: 0

  cmd_sally_set_pop_bumper_timer_running_1:
    v_sally_pop_bumper_timer_running:
      action: set
      int: 1

  cmd_sally_set_pop_bumper_timer_running_0:
    v_sally_pop_bumper_timer_running:
      action: set
      int: 0

  cmd_set_sally_left_orbit_hit:
    v_sally_left_orbit_hit:
      action: set
      int: 1

  cmd_set_sally_left_ramp_hit:
    v_sally_left_ramp_hit:
      action: set
      int: 1

  cmd_set_sally_right_ramp_hit:
    v_sally_right_ramp_hit:
      action: set
      int: 1

  cmd_set_sally_right_orbit_hit:
    v_sally_right_orbit_hit:
      action: set
      int: 1

  sally_pop_bumper_hit:
    v_sally_pop_bumper_counter: -1

  sally_shot_hit{current_player.v_sally_shot_counter<4}:
    v_sally_shot_counter: 1

##################################################
# Slides
##################################################

slides:
  sally_intro_slide:
    widgets:
      - type: image
        image: dinner_with_sally_intro_v4
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sally_pop_bumper_slide:
    widgets:
      - type: image
        image: sally_struggle_v2

  sally_pop_bumper_eyes_slide:
    widgets:
      - type: text
        text: (player|v_sally_pop_bumper_counter)
        style: small
        anchor_x: left
        anchor_y: bottom
        x: 4
        y: 2
      - type: image
        image: sally_pop_bumper_v1

  sally_shots_slide:
    widgets:
      - type: image
        image: sally_struggle_for_shots_v1

  sally_shot_hit_slide_1:
    widgets:
      - type: image
        image: sally_left_hand_cu_v1

  sally_shot_hit_slide_2:
    widgets:
      - type: image
        image: sally_right_hand_cu_v1

  sally_shot_hit_slide_3:
    widgets:
      - type: image
        image: sally_left_hand_free_v1

  sally_shot_hit_slide_4:
    widgets:
      - type: image
        image: sally_right_hand_free_v1

  sally_final_slide:
    widgets:
      - type: image
        image: shoot_slaughter_free_sally_v1 

  sally_complete_slide:
    widgets:
      - type: image
        image: sally_escape_v1

slide_player:
  cmd_sally_start_intro_slide:
    sally_intro_slide:
      priority: 500
      expire: 10s

  cmd_sally_play_pop_bumper_slide:
    sally_pop_bumper_slide:
      priority: 500

  cmd_sally_remove_pop_bumper_slide:
    sally_pop_bumper_slide:
      action: remove

  cmd_sally_show_eyes_slide:
    sally_pop_bumper_eyes_slide:
      priority: 1000

  cmd_sally_remove_eyes_slide:
    sally_pop_bumper_eyes_slide:
      action: remove

  cmd_sally_add_shots_slide:
    sally_shots_slide:
      priority: 500

  cmd_play_sally_escape_1:
    sally_shot_hit_slide_1:
      priority: 600
      expire: 2.9s

  cmd_play_sally_escape_2:
    sally_shot_hit_slide_2:
      priority: 600
      expire: 2.9s

  cmd_play_sally_escape_3:
    sally_shot_hit_slide_3:
      priority: 600
      expire: 2.3s

  cmd_play_sally_escape_4:
    sally_shot_hit_slide_4:
      priority: 600
      expire: 2.8s

  cmd_sally_remove_shots_slide:
    sally_shots_slide:
      action: remove

  cmd_sally_add_final_slide:
    sally_final_slide:
      priority: 700

  cmd_sally_add_complete_slide:
    sally_complete_slide:
      priority: 1000
      expire: 6.7s

##################################################
# Shows
##################################################

show_player:
  cmd_sally_clear_playfield_lights:
    med_flash:
      action: stop
      show_tokens:
        lights:
          - top_turbo_bumper
          - left_turbo_bumper
          - right_turbo_bumper

  cmd_sally_flash_pop_bumpers:
    med_flash:
      action: play
      show_tokens:
        lights:
          top_turbo_bumper,
          left_turbo_bumper,
          right_turbo_bumper

##################################################
# Light Player
##################################################

light_player:
  cmd_sally_clear_playfield_lights:
    left_orbit_arrow: 0
    basket_ramp_arrow: 0
    right_ramp_arrow: 0
    right_orbit_arrow: 0

  cmd_sally_light_left_orbit:
    left_orbit_arrow: ff

  cmd_sally_light_basket_ramp:
    basket_ramp_arrow: ff

  cmd_sally_light_right_ramp:
    right_ramp_arrow: ff

  cmd_sally_light_right_orbit:
    right_orbit_arrow: ff

  cmd_sally_light_slaughter_house:
    slaughter_house_arrow: ff


##################################################
# Sounds
##################################################

sound_player:
  cmd_sally_pop_bumper_sound_1:
    sally_pop_bumper_score_v1:
      action: play
      loops: 0

  cmd_sally_pop_bumper_sound_2:
    sally_pop_bumper_score_v2:
      action: play
      loops: 0

  cmd_sally_pop_bumper_sound_3:
    sally_pop_bumper_score_v3:
      action: play
      loops: 0

  cmd_sally_clear_pop_bumper_sound:
    sally_pop_bumper_score_v1:
      action: stop

    sally_pop_bumper_score_v2:
      action: stop

    sally_pop_bumper_score_v3:
      action: stop

  cmd_sally_start_intro_slide_sound:
    dinner_with_sally_v1_score:
      action: play
      loops: 0

  cmd_sally_play_complete_audio:
    sally_escape_score_v1:
      action: play
      loops: 0

  cmd_play_sally_bg_music_phase_1:
    sally_bg_music_phase_1:
      action: play
      volume: 0.3

  cmd_play_sally_bg_music_phase_2:
    sally_bg_music_phase_2:
      action: play
      volume: 0.3

  cmd_play_sally_escape_1:
    sally_hand_cu_score_v1:
      action: play
      loops: 0

  cmd_play_sally_escape_2:
    sally_hand_cu_score_v1:
      action: play
      loops: 0

  cmd_play_sally_escape_3:
    sally_left_hand_free_score_v1:
      action: play
      loops: 0

  cmd_play_sally_escape_4:
    sally_right_hand_free_score_v1:
      action: play
      loops: 0
