#config_version=5

mode:
  start_events:
    - cmd_start_mode_sally
  stop_events:
    - cmd_stop_mode_sally
  priority: 10000

##################################################
# Events
##################################################

event_player:
  mode_sally_started:
    cmd_disable_bh_mode_van:
    cmd_sally_set_state_starting:
    cmd_sally_set_reset_sally_pop_bumper_counter:
    cmd_sally_start_intro_slide:
    cmd_sally_start_intro_slide_sound:

  timer_sally_timer_1_complete:
    cmd_stop_sally_mode:

  slide_sally_intro_slide_removed:
    cmd_sally_after_intro_complete:

  cmd_sally_after_intro_complete:
    cmd_sally_set_state_pop_bumpers:
    cmd_play_sally_bg_music:
    cmd_eject_van_vuk_with_audio:
    cmd_sally_refresh_lights:
    cmd_sally_play_pop_bumper_slide:

  logicblock_sally_counter_complete:
    cmd_stop_sally_timer_1:

  #### Lights ####

  cmd_sally_refresh_lights:
    cmd_sally_clear_playfield_lights:
    cmd_sally_turn_on_playfield_lights:

  cmd_sally_turn_on_playfield_lights{current_player.v_sally_state=="pop_bumpers"}:
    cmd_sally_show_pop_bumpers:

  #### Switch Hits ###

  top_turbo_bumper_hit{current_player.v_sally_state=="pop_bumpers"}:
    - sally_pop_bumper_hit

  left_turbo_bumper_hit{current_player.v_sally_state=="pop_bumpers"}:
    - sally_pop_bumper_hit

  right_turbo_bumper_hit{current_player.v_sally_state=="pop_bumpers"}:
    - sally_pop_bumper_hit

##################################################
# Timers
##################################################

timers:
  sally_timer_1:
    start_value: 0
    end_value: 60
    tick_interval: 1s
    direction: up
    start_running: True
    control_events:
      - action: stop
        event: cmd_stop_sally_timer_1

##################################################
# Counters
##################################################

counters:
  sally_counter:
    count_events: cmd_add_sally_counter
    direction: down
    # remember to set the base state
    starting_count: 20
    disable_on_complete: True
    reset_on_complete: False
    count_complete_value: 0
    persist_state: True

##################################################
# Variables
##################################################

variable_player:
  cmd_sally_set_state_starting:
    v_sally_state:
      action: set
      string: "starting"

  cmd_sally_set_state_pop_bumpers:
    v_sally_state:
      action: set
      string: "pop_bumpers"

  cmd_sally_set_reset_sally_pop_bumper_counter:
    # remember to set the starting_count
    v_sally_pop_bumper_counter:
      action: set
      int: 20

  sally_pop_bumper_hit:
    v_sally_pop_bumper_counter: -1

##################################################
# Slides
##################################################

slides:
  sally_intro_slide:
    widgets:
      - type: image
        image: dinner_with_sally_intro_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sally_pop_bumper_slide:
    widgets:
      - type: text
        text: (player|v_sally_pop_bumper_counter)
        style: small

slide_player:
  cmd_sally_start_intro_slide:
    sally_intro_slide:
      priority: 500
      expire: 10s

  cmd_sally_play_pop_bumper_slide:
    sally_pop_bumper_slide:
      priority: 500

  cmd_sally_remove_pop_bumper_slide:
    sally_pop_bumper_slide:
      action: remove

##################################################
# Shows
##################################################

show_player:
  cmd_sally_clear_playfield_lights:
    med_flash:
      action: stop
      show_tokens:
        lights:
          - top_turbo_bumper
          - left_turbo_bumper
          - right_turbo_bumper

  cmd_sally_show_pop_bumpers:
    med_flash:
      action: play
      show_tokens:
        lights:
          top_turbo_bumper,
          left_turbo_bumper,
          right_turbo_bumper


##################################################
# Sounds
##################################################

sound_player:
  cmd_sally_start_intro_slide_sound:
    dinner_with_sally_v1_score:
      action: play
      loops: 0
