#config_version=5

mode:
  start_events:
    - cmd_start_mode_grave
  stop_events:
    - cmd_stop_mode_grave
  priority: 10000

##################################################
# Events
##################################################

event_player:
  mode_grave_started:
    cmd_disable_bh_mode_van:
    cmd_grave_set_state_base:
    cmd_grave_set_mutiplier_to_base:
    cmd_grave_start_intro_slide:
    cmd_grave_start_intro_slide_sound:

  multiball_grave_multiball_ended:
    cmd_stop_grave_mode:

  slide_grave_intro_slide_removed:
    cmd_grave_after_intro_complete:

  cmd_grave_after_intro_complete:
    cmd_start_grave_multiball:
    cmd_start_shoot_again_flash:
    cmd_grave_set_state_combo_1_shooting:
    cmd_play_grave_bg_music:
    cmd_eject_van_vuk_with_audio:
    cmd_grave_refresh_lights:

  multiball_grave_multiball_shoot_again_ended:
    cmd_stop_shoot_again_flash:

  #### Lights ####

  cmd_grave_refresh_lights:
    cmd_grave_clear_playfield_lights:
    cmd_grave_turn_on_playfield_lights:

  #### Shots ####

  right_ramp_hit:
    cmd_grave_combo_ramp_hit:

  left_ramp_hit:
    cmd_grave_combo_ramp_hit:

  left_orbit_hit:
    cmd_grave_combo_ramp_hit:

  right_orbit_hit:
    cmd_grave_combo_ramp_hit:

  s_captive_ball_target_active:
    cmd_grave_single_jackpot_hit:

  s_super_duper_jackpot_active:
    cmd_grave_double_jackpot_hit:

  cmd_grave_combo_ramp_hit{current_player.v_grave_state=="base"}:
    cmd_grave_set_state_combo:
    cmd_grave_refresh_lights:
    cmd_grave_increase_multiplier:
    cmd_grave_start_combo_timer:

  cmd_grave_combo_ramp_hit{current_player.v_grave_state=="combo"}:
    cmd_grave_increase_multiplier:
    cmd_grave_combo_timer_restart:

  cmd_grave_single_jackpot_hit:
    cmd_grave_reset_values:
    cmd_grave_refresh_lights:

  cmd_grave_double_jackpot_hit:
    cmd_grave_reset_values:
    cmd_grave_refresh_lights:

  cmd_grave_reset_values:
    cmd_grave_set_state_base:
    cmd_grave_set_mutiplier_to_base:

  timer_grave_combo_timer_complete:
    cmd_grave_reset_values:
    cmd_grave_refresh_lights:

##################################################
# Devices
##################################################

multiballs:
  grave_multiball:
    ball_count: 1
    ball_count_type: add
    shoot_again: 25s
    start_events: cmd_start_grave_multiball

##################################################
# Logic
##################################################

timers:
  grave_combo_timer:
    start_value: 0
    end_value: 6
    tick_interval: 1s
    direction: up
    start_running: False
    control_events:
      - event: cmd_grave_combo_timer_stop
        action: stop
      - event: cmd_grave_combo_timer_restart
        action: restart

##################################################
# Variables
##################################################

variable_player:
  cmd_grave_set_state_base:
    v_grave_state:
      action: set
      string: "base"

  cmd_grave_set_state_combo:
    v_grave_state:
      action: set
      string: "combo"

  cmd_grave_set_mutiplier_to_base:
    v_grave_multiplier:
      action: set
      float: 0.0

  cmd_grave_increase_multiplier:
    v_grave_multiplier:
      action: set
      float: current_player.v_grave_multiplier + 0.5

  cmd_grave_single_jackpot_hit.100:
    score: 1000000 * current_player.v_grave_multiplier

  cmd_grave_double_jackpot_hit.100:
    score: 1000000 * 2 * current_player.v_grave_multiplier

##################################################
# Sites and Sounds
##################################################

slides:
  grave_intro_slide:
    widgets:
      - type: image
        image: grave_robber_intro_v3
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

slide_player:
  cmd_grave_start_intro_slide:
    grave_intro_slide:
      priority: 500
      expire: 6.1s

sound_player:
  cmd_grave_start_intro_slide_sound:
    grave_robber_intro_score_v1:
      action: play
      loops: 0

  cmd_play_grave_bg_music:
    grave_bg_music:
      action: play
      loops: -1
      volume: 2

show_player:

  cmd_start_shoot_again_flash:
    fast_flash:
      action: play
      show_tokens:
        light: shoot_again

  cmd_stop_shoot_again_flash:
    fast_flash:
      action: stop
      show_tokens:
        light: shoot_again

  ### Lights ###

  cmd_grave_turn_on_playfield_lights{current_player.v_grave_state=="base"}:
    on:
      action: play
      show_tokens:
        lights:
          basket_ramp_arrow,
          right_ramp_arrow,
          left_orbit_arrow,
          right_orbit_arrow

  cmd_grave_turn_on_playfield_lights{current_player.v_grave_state=="combo"}:
    med_flash:
      action: play
      show_tokens:
        lights:
          basket_ramp_arrow,
          right_ramp_arrow,
          left_orbit_arrow,
          right_orbit_arrow

    fast_flash:
      action: play
      show_tokens:
        lights:
          captive_ball_arrow,
          super_duper_jackpot

  cmd_grave_clear_playfield_lights:
    on:
      action: stop
      show_tokens:
        lights:
          - basket_ramp_arrow
          - right_ramp_arrow
          - left_orbit_arrow
          - right_orbit_arrow

    med_flash:
      action: stop
      show_tokens:
        lights:
          - basket_ramp_arrow
          - right_ramp_arrow
          - left_orbit_arrow
          - right_orbit_arrow

    slow_flash:
      action: stop
      show_tokens:
        lights:
          - captive_ball_arrow
          - super_duper_jackpot

    fast_flash:
      action: stop
      show_tokens:
        lights:
          - captive_ball_arrow
          - super_duper_jackpot
