#config_version=5

mode:
  start_events:
    - cmd_start_mode_grandpa
  stop_events:
    - cmd_stop_mode_grandpa
  priority: 10000

##################################################
# Events
##################################################

event_player:
  mode_grandpa_started:
    cmd_mode_intro_started:
    cmd_disable_bh_mode_van:
    cmd_grandpa_set_state_starting:
    cmd_grandpa_start_intro_slide:
    cmd_grandpa_start_intro_slide_sound:

  timer_grandpa_mode_timer_complete:
    cmd_stop_grandpa_mode:

  slide_grandpa_hit_sally_slide_3_removed:
    cmd_stop_grandpa_mode:

  slide_grandpa_intro_slide_removed:
    cmd_grandpa_after_intro_complete:

  cmd_grandpa_after_intro_complete:
    cmd_mode_intro_complete:
    cmd_grandpa_set_state_combo_1_shooting:
    cmd_play_grandpa_bg_music:
    cmd_eject_van_vuk_with_audio:
    cmd_grandpa_refresh_lights:

  cmd_grandpa_right_ramp_hit:
    cmd_activate_diverter:
    cmd_grandpa_combo_timer_restart:
    cmd_grandpa_refresh_lights:
    cmd_grandpa_start_lift_hammer_slide:
    cmd_add_grandpa_rando_sound_counter:

  cmd_grandpa_combo_missed:
    cmd_grandpa_refresh_lights:
    cmd_grandpa_start_drop_hammer_slide:
    cmd_grandpa_miss_sally_sound:
    cmd_grandpa_remove_background_slide:

  cmd_grandpa_combo_completed:
    cmd_grandpa_refresh_lights:
    cmd_grandpa_remove_background_slide:


  #### Lights ####

  cmd_grandpa_refresh_lights:
    cmd_grandpa_clear_playfield_lights:
    cmd_grandpa_turn_on_playfield_lights:

  cmd_grandpa_turn_on_playfield_lights{current_player.v_grandpa_state=="combo_1_shooting"}:
    cmd_grandpa_show_right_ramp_light:

  cmd_grandpa_turn_on_playfield_lights{current_player.v_grandpa_state=="combo_2_shooting"}:
    cmd_grandpa_show_right_ramp_light:

  cmd_grandpa_turn_on_playfield_lights{current_player.v_grandpa_state=="combo_3_shooting"}:
    cmd_grandpa_show_right_ramp_light:

  cmd_grandpa_turn_on_playfield_lights{current_player.v_grandpa_state=="combo_1_shot"}:
    cmd_grandpa_show_right_basket_light:

  cmd_grandpa_turn_on_playfield_lights{current_player.v_grandpa_state=="combo_2_shot"}:
    cmd_grandpa_show_right_basket_light:

  cmd_grandpa_turn_on_playfield_lights{current_player.v_grandpa_state=="combo_3_shot"}:
    cmd_grandpa_show_right_basket_light:

  #### Shots ####

  right_ramp_hit{current_player.v_grandpa_state=="combo_1_shooting"}:
    cmd_grandpa_score_right_ramp:
    cmd_grandpa_set_state_combo_1_shot:
    cmd_grandpa_right_ramp_hit:

  right_ramp_hit{current_player.v_grandpa_state=="combo_2_shooting"}:
    cmd_grandpa_score_right_ramp:
    cmd_grandpa_set_state_combo_2_shot:
    cmd_grandpa_right_ramp_hit:

  right_ramp_hit{current_player.v_grandpa_state=="combo_3_shooting"}:
    cmd_grandpa_score_right_ramp:
    cmd_grandpa_set_state_combo_3_shot:
    cmd_grandpa_right_ramp_hit:

  timer_grandpa_combo_timer_complete{current_player.v_grandpa_state=="combo_1_shot"}:
    cmd_grandpa_set_state_combo_1_shooting:
    cmd_grandpa_combo_missed:

  timer_grandpa_combo_timer_complete{current_player.v_grandpa_state=="combo_2_shot"}:
    cmd_grandpa_set_state_combo_2_shooting:
    cmd_grandpa_combo_missed:

  timer_grandpa_combo_timer_complete{current_player.v_grandpa_state=="combo_3_shot"}:
    cmd_grandpa_set_state_combo_3_shooting:
    cmd_grandpa_combo_missed:

  left_ramp_hit{current_player.v_grandpa_state=="combo_1_shot"}:
    cmd_grandpa_score_left_ramp_1:
    cmd_grandpa_combo_timer_stop:
    cmd_grandpa_start_hit_sally_slide_1:
    cmd_grandpa_hit_sally_sound_1:
    cmd_grandpa_set_state_combo_2_shooting:
    cmd_grandpa_combo_completed:

  left_ramp_hit{current_player.v_grandpa_state=="combo_2_shot"}:
    cmd_grandpa_score_left_ramp_2:
    cmd_grandpa_combo_timer_stop:
    cmd_grandpa_start_hit_sally_slide_2:
    cmd_grandpa_hit_sally_sound_2:
    cmd_grandpa_set_state_combo_3_shooting:
    cmd_grandpa_combo_completed:

  left_ramp_hit{current_player.v_grandpa_state=="combo_3_shot"}:
    cmd_grandpa_score_left_ramp_3:
    cmd_grandpa_combo_timer_stop:
    cmd_grandpa_start_hit_sally_slide_3:
    cmd_grandpa_hit_sally_sound_3:
    cmd_grandpa_set_state_winning:
    cmd_grandpa_combo_completed:


##################################################
# Logic
##################################################

timers:
  grandpa_mode_timer:
    start_value: 0
    end_value: 80
    tick_interval: 1s
    direction: up
    start_running: True
    control_events:
      - event: cmd_grandpa_mode_timer_add
        action: add
        value: 8

  grandpa_combo_timer:
    start_value: 0
    end_value: 8
    tick_interval: 1s
    direction: up
    start_running: False
    control_events:
      - event: cmd_grandpa_combo_timer_stop
        action: stop
      - event: cmd_grandpa_combo_timer_restart
        action: restart

##################################################
# Variables
##################################################

variable_player:
  cmd_grandpa_set_state_starting:
    v_grandpa_state:
      action: set
      string: "starting"

  cmd_grandpa_set_state_combo_1_shooting:
    v_grandpa_state:
      action: set
      string: "combo_1_shooting"

  cmd_grandpa_set_state_combo_2_shooting:
    v_grandpa_state:
      action: set
      string: "combo_2_shooting"

  cmd_grandpa_set_state_combo_3_shooting:
    v_grandpa_state:
      action: set
      string: "combo_3_shooting"

  cmd_grandpa_set_state_combo_1_shot:
    v_grandpa_state:
      action: set
      string: "combo_1_shot"

  cmd_grandpa_set_state_combo_2_shot:
    v_grandpa_state:
      action: set
      string: "combo_2_shot"

  cmd_grandpa_set_state_combo_3_shot:
    v_grandpa_state:
      action: set
      string: "combo_3_shot"

##################################################
# Sites and Sounds
##################################################

slides:
  grandpa_intro_slide:
    widgets:
      - type: image
        image: hammer_time_intro_v3
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  grandpa_lift_hammer_slide:
    widgets:
      - type: image
        image: grandpa_pickup_sledge_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  grandpa_drop_hammer_slide:
    widgets:
      - type: image
        image: grandpa_miss_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  grandpa_hit_sally_slide_1:
    widgets:
      - type: image
        image: grandpa_hit_1_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  grandpa_hit_sally_slide_2:
    widgets:
      - type: image
        image: grandpa_hit_2_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  grandpa_hit_sally_slide_3:
    widgets:
      - type: image
        image: grandpa_hit_3_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

slide_player:
  cmd_grandpa_start_intro_slide:
    grandpa_intro_slide:
      priority: 500
      expire: 6.1s

  cmd_grandpa_start_lift_hammer_slide:
    grandpa_lift_hammer_slide:
      priority: 600
      expire: 7s

  cmd_grandpa_start_drop_hammer_slide:
    grandpa_drop_hammer_slide:
      priority: 700
      expire: 3.4s

  cmd_grandpa_start_hit_sally_slide_1:
    grandpa_hit_sally_slide_1:
      priority: 800
      expire: 3.6s

  cmd_grandpa_start_hit_sally_slide_2:
    grandpa_hit_sally_slide_2:
      priority: 800
      expire: 4s

  cmd_grandpa_start_hit_sally_slide_3:
    grandpa_hit_sally_slide_3:
      priority: 800
      expire: 4.8s

sound_player:
  cmd_grandpa_start_intro_slide_sound:
    hammer_time_intro_score_v1:
      action: play
      loops: 0

  cmd_play_grandpa_bg_music:
    grandpa_bg_music:
      action: play
      loops: -1
      volume: 0.2

  cmd_grandpa_hit_sally_sound_1:
    grandpa_hit_1_sound_v1:
      action: play
      loops: 0

  cmd_grandpa_hit_sally_sound_2:
    grandpa_hit_2_sound_v1:
      action: play
      loops: 0

  cmd_grandpa_hit_sally_sound_3:
    grandpa_hit_3_sound_v1:
      action: play
      loops: 0

  cmd_grandpa_miss_sally_sound:
    grandpa_miss_score_v1_1:
      action: play
      loops: 0

  counter_grandpa_rando_sound_counter_hit{count==1}:
    grandpa_pickup_sledge_score_v1_1:
      action: play
      loops: 0

  counter_grandpa_rando_sound_counter_hit{count==2}:
    grandpa_pickup_sledge_score_v1_1:
      action: play
      loops: 0

  counter_grandpa_rando_sound_counter_hit{count==3}:
    grandpa_pickup_sledge_score_v1_1:
      action: play
      loops: 0

  logicblock_grandpa_rando_sound_counter_complete:
    grandpa_pickup_sledge_score_v1_1:
      action: play
      loops: 0

show_player:

  ## Lights ##

  cmd_grandpa_clear_playfield_lights:
    med_flash:
      action: stop
      show_tokens:
        lights:
          - basket_ramp_arrow
          - right_ramp_arrow

  cmd_grandpa_show_right_ramp_light:
    med_flash:
      action: play
      show_tokens:
        lights:
          right_ramp_arrow

  cmd_grandpa_show_right_basket_light:
    med_flash:
      action: play
      show_tokens:
        lights:
          basket_ramp_arrow

counters:
  grandpa_rando_sound_counter:
    count_events: cmd_add_grandpa_rando_sound_counter
    disable_on_complete: False
    reset_on_complete: True
    count_complete_value: 4
