#config_version=5

mode:
  start_events:
    - cmd_start_mode_escape_multiball
  stop_events:
    - cmd_stop_mode_escape_multiball
  priority: 500

##################################################
# Events and Variables
##################################################

variable_player:

  cmd_escape_multiball_reset_jackpot_variables:
    v_escape_jackpot_captive_ball_collected:
      action: set
      int: 0
    v_escape_jackpot_left_ramp_collected:
      action: set
      int: 0
    v_escape_jackpot_left_orbit_collected:
      action: set
      int: 0
    v_escape_jackpot_right_ramp_collected:
      action: set
      int: 0
    v_escape_jackpot_slaughter_house_collected:
      action: set
      int: 0
    v_escape_jackpot_right_orbit_collected:
      action: set
      int: 0

  cmd_escape_multiball_jackpot_variable_left_ramp:
    v_escape_jackpot_left_ramp_collected:
      action: set
      int: 1
  cmd_escape_multiball_jackpot_variable_left_orbit:
    v_escape_jackpot_left_orbit_collected:
      action: set
      int: 1
  cmd_escape_multiball_jackpot_variable_right_ramp:
    v_escape_jackpot_right_ramp_collected:
      action: set
      int: 1
  cmd_escape_multiball_jackpot_variable_slaughter_house:
    v_escape_jackpot_slaughter_house_collected:
      action: set
      int: 1
  cmd_escape_multiball_jackpot_variable_right_orbit:
    v_escape_jackpot_right_orbit_collected:
      action: set
      int: 1

  cmd_set_escape_multiball_state.1{state=="ready"}:
    v_escape_multiball_state:
      action: set
      string: "ready"

  cmd_set_escape_multiball_state.2{state=="captive_shot"}:
    v_escape_multiball_state:
      action: set
      string: "captive_shot"

  cmd_set_escape_multiball_state.3{state=="super_jackpot"}:
    v_escape_multiball_state:
      action: set
      string: "super_jackpot"

event_player:

  mode_escape_multiball_started:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_ready
        type: string
    cmd_escape_multiball_reset_jackpot_variables:
    cmd_start_escape_multiball:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_start_kids:
    cmd_escape_multiball_shot_accrual_reset:

  ## control flow ##
  
  cmd_escape_multiball_refresh.1{current_player.v_escape_multiball_state=="ready"}:
    cmd_turn_on_escape_multiball_jackpot_lights:
    cmd_escape_multiball_turn_off_light_captive_ball:
    cmd_escpae_multiball_turn_off_super_jackpot_lights:
  cmd_escape_multiball_refresh.2{current_player.v_escape_multiball_state=="captive_shot"}:
    cmd_turn_off_escape_multiball_jackpot_lights:
    cmd_escape_multiball_turn_on_light_captive_ball:
    cmd_escpae_multiball_turn_off_super_jackpot_lights:
  cmd_escape_multiball_refresh.3{current_player.v_escape_multiball_state=="super_jackpot"}:
    cmd_escape_multiball_turn_off_light_captive_ball:
    cmd_turn_off_escape_multiball_jackpot_lights:
    cmd_escpae_multiball_turn_on_super_jackpot_lights:

  cmd_escape_multiball_captive_ball_hit.1{device.accruals.escape_multiball_shot_accrual.completed}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_super_jackpot
        type: string
    cmd_escape_multiball_refresh:

  cmd_escape_multiball_captive_ball_hit.2{not device.accruals.escape_multiball_shot_accrual.completed}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_ready
        type: string
    cmd_escape_multiball_refresh:
    

  multiball_escape_multiball_ended:
    - cmd_escape_multiball_reset_jackpot_variables
    - cmd_stop_escape_multiball_mode
    - cmd_escape_multiball_shot_accrual_reset

  ## lights ##

  cmd_turn_on_escape_multiball_jackpot_lights.1{current_player.v_escape_jackpot_slaughter_house_collected==0}:
    - cmd_escape_multiball_turn_on_light_slaughter_house
  cmd_turn_on_escape_multiball_jackpot_lights.3{current_player.v_escape_jackpot_left_orbit_collected==0}:
    - cmd_escape_multiball_turn_on_light_left_orbit
  cmd_turn_on_escape_multiball_jackpot_lights.4{current_player.v_escape_jackpot_left_ramp_collected==0}:
    - cmd_escape_multiball_turn_on_light_left_ramp
  cmd_turn_on_escape_multiball_jackpot_lights.5{current_player.v_escape_jackpot_right_ramp_collected==0}:
    - cmd_escape_multiball_turn_on_light_right_ramp
  cmd_turn_on_escape_multiball_jackpot_lights.6{current_player.v_escape_jackpot_right_orbit_collected==0}:
    - cmd_escape_multiball_turn_on_light_right_orbit

  cmd_turn_off_escape_multiball_jackpot_lights:
    cmd_escape_multiball_turn_off_light_slaughter_house:
    cmd_escape_multiball_turn_off_light_left_orbit:
    cmd_escape_multiball_turn_off_light_left_ramp:
    cmd_escape_multiball_turn_off_light_right_ramp:
    cmd_escape_multiball_turn_off_light_right_orbit:

  ## config hack ##
  cmd_escape_multiball_show_safe_jerry:
    cmd_bobo_config_hack
  cmd_escape_multiball_show_safe_franklin:
    cmd_bobo_config_hack
  cmd_escape_multiball_show_safe_pam:
    cmd_bobo_config_hack
  cmd_escape_multiball_show_safe_sally:
    cmd_bobo_config_hack
  cmd_escape_multiball_show_safe_kirk:
    cmd_bobo_config_hack

  ## switches ##

  s_captive_ball_target_active{current_player.v_escape_multiball_state=="captive_shot"}:
    cmd_escape_multiball_captive_ball_jackpot:
    cmd_escape_multiball_captive_ball_hit:

  s_slaughter_house_target_active{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_slaughter_house_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_slaughter_house:
    cmd_escape_multiball_accrual_slaughter_house:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_jerry:
  left_orbit_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_left_orbit_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_left_orbit:
    cmd_escape_multiball_accrual_left_orbit:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_franklin:
  left_ramp_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_left_ramp_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_left_ramp:
    cmd_escape_multiball_accrual_left_ramp:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_pam:
  right_ramp_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_right_ramp_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_right_ramp:
    cmd_escape_multiball_accrual_right_ramp:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_sally:
  right_orbit_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_right_orbit_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_right_orbit:
    cmd_escape_multiball_accrual_right_orbit:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_kirk:

  s_super_duper_jackpot_active{current_player.v_escape_multiball_state=="super_jackpot"}:
    cmd_escape_multiball_shot_accrual_reset:
    cmd_escape_multiball_reset_jackpot_variables:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_ready
        type: string
    cmd_escape_multiball_super_jackpot:
    cmd_escape_multiball_refresh:

##################################################
# Logicblocks
##################################################

accruals:
  escape_multiball_shot_accrual:
    events:
      - cmd_escape_multiball_accrual_slaughter_house
      - cmd_escape_multiball_accrual_left_orbit
      - cmd_escape_multiball_accrual_left_ramp
      - cmd_escape_multiball_accrual_right_ramp
      - cmd_escape_multiball_accrual_right_orbit
    reset_events:
      cmd_escape_multiball_shot_accrual_reset:
    reset_on_complete: False
    disable_on_complete: False

##################################################
# Devices
##################################################

multiballs:
  escape_multiball:
    ball_count: 2
    ball_count_type: add
    shoot_again: 5s
    start_events: cmd_start_escape_multiball

###################################################
# Sound & Graphics
###################################################

show_player:
  cmd_escape_multiball_start_leatherface_chase_show:
    escape_multiball_leatherface_chase:
      priority: 2000
      action: play
      loops: -1
  cmd_escape_multiball_stop_leatherface_chase_show:
    escape_multiball_leatherface_chase:
      action: stop 
  cmd_escape_multiball_start_kids:
    escape_multiball_kids:
      priority: 1000
      action: play
      loops: -1
  cmd_escape_multiball_stop_kids:
    escape_multiball_kids:
      action: stop 

light_player:

  # jackpot lights

  cmd_escape_multiball_turn_off_jackpot_lights:
    left_orbit_arrow: 0
    basket_ramp_arrow: 0
    slaughter_house_arrow: 0
    right_ramp_arrow: 0
    right_orbit_arrow: 0

  cmd_escape_multiball_turn_on_light_slaughter_house:
    slaughter_house_arrow: ff
  cmd_escape_multiball_turn_on_light_captive_ball:
    captive_ball_arrow: ff
  cmd_escape_multiball_turn_on_light_left_orbit:
    left_orbit_arrow: ff
  cmd_escape_multiball_turn_on_light_left_ramp:
    basket_ramp_arrow: ff
  cmd_escape_multiball_turn_on_light_right_ramp:
    right_ramp_arrow: ff
  cmd_escape_multiball_turn_on_light_right_orbit:
    right_orbit_arrow: ff

  cmd_escape_multiball_turn_off_light_slaughter_house:
    slaughter_house_arrow: 0
  cmd_escape_multiball_turn_off_light_captive_ball:
    captive_ball_arrow: 0
  cmd_escape_multiball_turn_off_light_left_orbit:
    left_orbit_arrow: 0
  cmd_escape_multiball_turn_off_light_left_ramp:
    basket_ramp_arrow: 0
  cmd_escape_multiball_turn_off_light_right_ramp:
    right_ramp_arrow: 0
  cmd_escape_multiball_turn_off_light_right_orbit:
    right_orbit_arrow: 0

  cmd_escpae_multiball_turn_on_super_jackpot_lights:
    super_duper_jackpot: ff
  cmd_escpae_multiball_turn_off_super_jackpot_lights:
    super_duper_jackpot: 0
