#config_version=5

mode:
  start_events:
    - cmd_start_mode_escape_multiball
  stop_events:
    - cmd_stop_mode_escape_multiball
  priority: 10000

##################################################
# Variables
##################################################

variable_player:

  cmd_escape_multiball_reset_jackpot_variables:
    v_escape_jackpot_left_ramp_collected:
      action: set
      int: 0
    v_escape_jackpot_left_orbit_collected:
      action: set
      int: 0
    v_escape_jackpot_right_ramp_collected:
      action: set
      int: 0
    v_escape_jackpot_slaughter_house_collected:
      action: set
      int: 0
    v_escape_jackpot_right_orbit_collected:
      action: set
      int: 0

  # Franklin
  cmd_escape_multiball_jackpot_variable_left_orbit:
    v_escape_jackpot_left_orbit_collected:
      action: set
      int: 1
  # Pam
  cmd_escape_multiball_jackpot_variable_left_ramp:
    v_escape_jackpot_left_ramp_collected:
      action: set
      int: 1
  # Jerry
  cmd_escape_multiball_jackpot_variable_slaughter_house:
    v_escape_jackpot_slaughter_house_collected:
      action: set
      int: 1
  # Sally
  cmd_escape_multiball_jackpot_variable_right_ramp:
    v_escape_jackpot_right_ramp_collected:
      action: set
      int: 1
  # Kirk
  cmd_escape_multiball_jackpot_variable_right_orbit:
    v_escape_jackpot_right_orbit_collected:
      action: set
      int: 1

  cmd_escape_set_last_saved_kid_franklin:
    v_escape_last_saved_kid:
      action: set
      string: "franklin"

  cmd_escape_set_last_saved_kid_pam:
    v_escape_last_saved_kid:
      action: set
      string: "pam"

  cmd_escape_set_last_saved_kid_jerry:
    v_escape_last_saved_kid:
      action: set
      string: "jerry"

  cmd_escape_set_last_saved_kid_sally:
    v_escape_last_saved_kid:
      action: set
      string: "sally"

  cmd_escape_set_last_saved_kid_kirk:
    v_escape_last_saved_kid:
      action: set
      string: "kirk"

  cmd_set_escape_multiball_state.1{state=="ready"}:
    v_escape_multiball_state:
      action: set
      string: "ready"

  cmd_set_escape_multiball_state.2{state=="captive_shot"}:
    v_escape_multiball_state:
      action: set
      string: "captive_shot"

  cmd_set_escape_multiball_state.3{state=="super_jackpot"}:
    v_escape_multiball_state:
      action: set
      string: "super_jackpot"

  cmd_escape_shoot_captive_ball_vo_fired_off:
    v_escape_shoot_captive_ball_vo_fired:
      action: set
      int: 0

  cmd_escape_shoot_captive_ball_vo_fired_on:
    v_escape_shoot_captive_ball_vo_fired:
      action: set
      int: 1

##################################################
# Events
##################################################

event_player:

  mode_escape_multiball_started:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_ready
        type: string
    cmd_escape_multiball_reset_jackpot_variables:
    cmd_start_escape_multiball:
    cmd_escape_multiball_show_intro_show:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_shot_accrual_reset:
    cmd_escape_shoot_captive_ball_vo_fired_off:

  ## control flow ##
  cmd_escape_multiball_refresh.1{current_player.v_escape_multiball_state=="ready"}:
    cmd_turn_on_escape_multiball_jackpot_lights:
    cmd_escape_multiball_turn_off_light_captive_ball:
    cmd_escape_multiball_turn_off_super_jackpot_lights:
    # shows
    cmd_escape_multiball_stop_super_jackpot_show:
    cmd_escape_multiball_stop_leatherface_chase_show:
    cmd_escape_multiball_start_kids:
  cmd_escape_multiball_refresh.2{current_player.v_escape_multiball_state=="captive_shot"}:
    cmd_turn_off_escape_multiball_jackpot_lights:
    cmd_escape_multiball_turn_on_light_captive_ball:
    cmd_escape_multiball_turn_off_super_jackpot_lights:
    # shows
    cmd_escape_multiball_stop_super_jackpot_show:
    cmd_start_escape_leatherface_show_timer:

  cmd_escape_multiball_refresh.3{current_player.v_escape_multiball_state=="super_jackpot"}:
    cmd_escape_multiball_turn_off_light_captive_ball:
    cmd_turn_off_escape_multiball_jackpot_lights:
    cmd_escape_multiball_turn_on_super_jackpot_lights:
    # shows
    cmd_escape_multiball_stop_leatherface_chase_show:
    cmd_escape_multiball_start_super_jackpot_show:
    cmd_escape_multiball_play_start_super_jackpot_sound:

  cmd_escape_multiball_captive_ball_hit.1{device.accruals.escape_multiball_shot_accrual.completed}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_super_jackpot
        type: string
    cmd_escape_multiball_refresh:

  cmd_escape_multiball_captive_ball_hit.2{not device.accruals.escape_multiball_shot_accrual.completed}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_ready
        type: string
    cmd_escape_multiball_refresh:

  multiball_escape_multiball_ended:
    - cmd_escape_multiball_reset_jackpot_variables
    - cmd_stop_escape_multiball_mode
    - cmd_escape_multiball_shot_accrual_reset

  ## shows ##

  timer_escape_multiball_leatherface_show_timer_complete{current_player.v_escape_multiball_state=="captive_shot"}:
    cmd_escape_multiball_stop_kids:
    cmd_escape_multiball_stop_super_jackpot_show:
    cmd_escape_multiball_start_leatherface_chase_show:
    cmd_start_shoot_captive_ball_vo_timer:

  ## sounds ##

  timer_escape_multiball_shoot_captive_ball_vo_timer_complete{current_player.v_escape_multiball_state=="captive_shot" and current_player.v_escape_shoot_captive_ball_vo_fired==0}:
    cmd_escape_multiball_play_shoot_captive_ball_vo:
    cmd_escape_shoot_captive_ball_vo_fired_on:

  timer_escape_multiball_hes_safe_vo_timer_complete:
    cmd_escape_multiball_play_hes_safe_vo:

  timer_escape_multiball_shes_safe_vo_timer_complete:
    cmd_escape_multiball_play_shes_safe_vo:

  timer_escape_multiball_kid_callout_timer_complete{current_player.v_escape_last_saved_kid=="franklin"}:
    cmd_escape_multiball_play_franklin_callout

  timer_escape_multiball_kid_callout_timer_complete{current_player.v_escape_last_saved_kid=="pam"}:
    cmd_escape_multiball_play_pam_callout

  timer_escape_multiball_kid_callout_timer_complete{current_player.v_escape_last_saved_kid=="kirk"}:
    cmd_escape_multiball_play_kirk_callout

  timer_escape_multiball_kid_callout_timer_complete{current_player.v_escape_last_saved_kid=="sally"}:
    cmd_escape_multiball_play_sally_callout

  timer_escape_multiball_kid_callout_timer_complete{current_player.v_escape_last_saved_kid=="jerry"}:
    cmd_escape_multiball_play_jerry_callout

  ## lights ##

  cmd_turn_on_escape_multiball_jackpot_lights.1{current_player.v_escape_jackpot_slaughter_house_collected==0}:
    - cmd_escape_multiball_turn_on_light_slaughter_house
  cmd_turn_on_escape_multiball_jackpot_lights.3{current_player.v_escape_jackpot_left_orbit_collected==0}:
    - cmd_escape_multiball_turn_on_light_left_orbit
  cmd_turn_on_escape_multiball_jackpot_lights.4{current_player.v_escape_jackpot_left_ramp_collected==0}:
    - cmd_escape_multiball_turn_on_light_left_ramp
  cmd_turn_on_escape_multiball_jackpot_lights.5{current_player.v_escape_jackpot_right_ramp_collected==0}:
    - cmd_escape_multiball_turn_on_light_right_ramp
  cmd_turn_on_escape_multiball_jackpot_lights.6{current_player.v_escape_jackpot_right_orbit_collected==0}:
    - cmd_escape_multiball_turn_on_light_right_orbit

  cmd_turn_off_escape_multiball_jackpot_lights:
    cmd_escape_multiball_turn_off_light_slaughter_house:
    cmd_escape_multiball_turn_off_light_left_orbit:
    cmd_escape_multiball_turn_off_light_left_ramp:
    cmd_escape_multiball_turn_off_light_right_ramp:
    cmd_escape_multiball_turn_off_light_right_orbit:

  ## switches ##

  s_captive_ball_target_active{current_player.v_escape_multiball_state=="captive_shot"}:
    cmd_escape_multiball_captive_ball_jackpot:
    cmd_escape_multiball_captive_ball_hit:
    cmd_escape_multiball_play_jackpot_show:
    cmd_escape_multiball_play_jackpot_sound:

  s_slaughter_house_target_active{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_slaughter_house_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_set_last_saved_kid_jerry:
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_slaughter_house:
    cmd_escape_multiball_accrual_slaughter_house:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_jerry:
    cmd_escape_multiball_play_safe_sound:
    cmd_start_hes_safe_vo_timer:
    cmd_escape_start_kid_callout_timer:
  left_orbit_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_left_orbit_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_set_last_saved_kid_franklin:
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_left_orbit:
    cmd_escape_multiball_accrual_left_orbit:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_franklin:
    cmd_escape_multiball_play_safe_sound:
    cmd_start_hes_safe_vo_timer:
    cmd_escape_start_kid_callout_timer:
  left_ramp_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_left_ramp_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_set_last_saved_kid_pam:
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_left_ramp:
    cmd_escape_multiball_accrual_left_ramp:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_pam:
    cmd_escape_multiball_play_safe_sound:
    cmd_start_shes_safe_vo_timer:
    cmd_escape_start_kid_callout_timer:
  right_ramp_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_right_ramp_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_set_last_saved_kid_sally:
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_right_ramp:
    cmd_escape_multiball_accrual_right_ramp:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_sally:
    cmd_escape_multiball_play_safe_sound:
    cmd_start_shes_safe_vo_timer:
    cmd_escape_start_kid_callout_timer:
  right_orbit_hit{current_player.v_escape_multiball_state=="ready" and current_player.v_escape_jackpot_right_orbit_collected==0}:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_captive_shot
        type: string
    cmd_escape_set_last_saved_kid_kirk:
    cmd_escape_multiball_jackpot:
    cmd_escape_multiball_jackpot_variable_right_orbit:
    cmd_escape_multiball_accrual_right_orbit:
    cmd_escape_multiball_refresh:
    cmd_escape_multiball_show_safe_kirk:
    cmd_escape_multiball_play_safe_sound:
    cmd_start_hes_safe_vo_timer:
    cmd_escape_start_kid_callout_timer:

  s_super_duper_jackpot_active{current_player.v_escape_multiball_state=="super_jackpot"}:
    cmd_escape_multiball_shot_accrual_reset:
    cmd_escape_multiball_reset_kid_variables:
    cmd_escape_multiball_reset_jackpot_variables:
    cmd_set_escape_multiball_state:
      state:
        value: machine.mv_escape_state_ready
        type: string
    cmd_escape_multiball_super_jackpot:
    cmd_escape_multiball_refresh:
    cmd_escape_play_super_jackpot_hit_show:
    cmd_escape_play_super_jackpot_hit_sound:

##################################################
# Logicblocks
##################################################

accruals:
  escape_multiball_shot_accrual:
    events:
      - cmd_escape_multiball_accrual_left_orbit
      - cmd_escape_multiball_accrual_left_ramp
      - cmd_escape_multiball_accrual_slaughter_house
      - cmd_escape_multiball_accrual_right_ramp
      - cmd_escape_multiball_accrual_right_orbit
    reset_events:
      cmd_escape_multiball_shot_accrual_reset:
    reset_on_complete: False
    disable_on_complete: False

##################################################
# Devices
##################################################

multiballs:
  escape_multiball:
    ball_count: 2
    ball_count_type: add
    shoot_again: 5s
    start_events: cmd_start_escape_multiball

timers:
  escape_multiball_leatherface_show_timer:
    start_value: 0
    end_value: 1
    tick_interval: 1.5s
    control_events:
      - action: restart
        event: cmd_start_escape_leatherface_show_timer
  escape_multiball_shoot_captive_ball_vo_timer:
    start_value: 0
    end_value: 1
    tick_interval: 1.5s
    control_events:
      - action: restart
        event: cmd_start_shoot_captive_ball_vo_timer
  escape_multiball_hes_safe_vo_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.5s
    control_events:
      - action: restart
        event: cmd_start_hes_safe_vo_timer
  escape_multiball_kid_callout_timer:
    start_value: 0
    end_value: 1
    tick_interval: 2.5s
    control_events:
      - action: restart
        event: cmd_escape_start_kid_callout_timer
  escape_multiball_shes_safe_vo_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.5s
    control_events:
      - action: restart
        event: cmd_start_shes_safe_vo_timer
  escape_multiball_random_vo_timer:
    start_value: 0
    end_value: 1
    tick_interval: 5s
    control_events:
      - action: restart
        event: cmd_start_random_vo_timer

###################################################
# Sound & Graphics
###################################################

show_player:

  cmd_escape_multiball_show_intro_show:
    escape_multiball_intro_description:
      priority: 20000
      action: play
      loops: 0

  cmd_escape_multiball_start_leatherface_chase_show:
    escape_multiball_leatherface_chase:
      priority: 10000
      action: play
      loops: -1

  cmd_escape_multiball_stop_leatherface_chase_show:
    escape_multiball_leatherface_chase:
      priority: 10000
      action: stop

  cmd_escape_multiball_start_super_jackpot_show:
    escape_multiball_super_jackpot:
      priority: 10000
      action: play
      loops: -1

  cmd_escape_multiball_stop_super_jackpot_show:
    escape_multiball_super_jackpot:
      priority: 10000
      action: stop

  cmd_escape_multiball_play_jackpot_show:
    escape_multiball_jackpot:
      priority: 10000
      action: play
      loops: 0

  cmd_escape_play_super_jackpot_hit_show:
    escape_multiball_super_jackpot_hit:
      priority: 10000
      action: play
      loops: 0

  cmd_escape_multiball_start_kids.10:
    escape_multiball_kids:
      priority: 10000
      action: play
      loops: -1
      show_tokens:
        franklin_safe_text_opacity: (current_player.v_escape_jackpot_left_orbit_collected)
        franklin_safe_bg_opacity: (current_player.v_escape_jackpot_left_orbit_collected * 0.3)
        pam_safe_text_opacity: (current_player.v_escape_jackpot_left_ramp_collected)
        pam_safe_bg_opacity: (current_player.v_escape_jackpot_left_ramp_collected * 0.3)
        jerry_safe_text_opacity: (current_player.v_escape_jackpot_slaughter_house_collected)
        jerry_safe_bg_opacity: (current_player.v_escape_jackpot_slaughter_house_collected * 0.3)
        sally_safe_text_opacity: (current_player.v_escape_jackpot_right_ramp_collected)
        sally_safe_bg_opacity: (current_player.v_escape_jackpot_right_ramp_collected * 0.3)
        kirk_safe_text_opacity: (current_player.v_escape_jackpot_right_orbit_collected)
        kirk_safe_bg_opacity: (current_player.v_escape_jackpot_right_orbit_collected * 0.3)

  cmd_escape_multiball_stop_kids:
    escape_multiball_kids:
      action: stop

  # Ball Save (needs to be here, did not work in the base.yaml)

  ball_save_multiball_start_enabled:
    on:
      show_tokens:
        lights: shoot_again

  ball_save_multiball_start_disabled:
    off:
      show_tokens:
        lights: shoot_again

  ball_save_multiball_start_grace_period:
    off:
      show_tokens:
        lights: shoot_again

light_player:

  # jackpot lights

  cmd_escape_multiball_turn_off_jackpot_lights:
    left_orbit_arrow: 0
    basket_ramp_arrow: 0
    slaughter_house_arrow: 0
    right_ramp_arrow: 0
    right_orbit_arrow: 0

  cmd_escape_multiball_turn_on_light_slaughter_house:
    slaughter_house_arrow: ff
  cmd_escape_multiball_turn_on_light_captive_ball:
    captive_ball_arrow: ff
  cmd_escape_multiball_turn_on_light_left_orbit:
    left_orbit_arrow: ff
  cmd_escape_multiball_turn_on_light_left_ramp:
    basket_ramp_arrow: ff
  cmd_escape_multiball_turn_on_light_right_ramp:
    right_ramp_arrow: ff
  cmd_escape_multiball_turn_on_light_right_orbit:
    right_orbit_arrow: ff

  cmd_escape_multiball_turn_off_light_slaughter_house:
    slaughter_house_arrow: 0
  cmd_escape_multiball_turn_off_light_captive_ball:
    captive_ball_arrow: 0
  cmd_escape_multiball_turn_off_light_left_orbit:
    left_orbit_arrow: 0
  cmd_escape_multiball_turn_off_light_left_ramp:
    basket_ramp_arrow: 0
  cmd_escape_multiball_turn_off_light_right_ramp:
    right_ramp_arrow: 0
  cmd_escape_multiball_turn_off_light_right_orbit:
    right_orbit_arrow: 0

  cmd_escape_multiball_turn_on_super_jackpot_lights:
    super_duper_jackpot: ff
  cmd_escape_multiball_turn_off_super_jackpot_lights:
    super_duper_jackpot: 0

sound_player:
  cmd_escape_multiball_play_jackpot_sound: escape_mb_jackpot_v2_score
  cmd_escape_multiball_play_safe_sound:
    safe_sound:
      volume: 1.0
  cmd_escape_multiball_play_shoot_captive_ball_vo:
    vo_kid_captive_ball:
      volume: 1.0
  cmd_escape_multiball_play_hes_safe_vo:
    vo_hes_safe:
      volume: 1.0
  cmd_escape_multiball_play_shes_safe_vo:
    vo_shes_safe:
      volume: 1.0
  cmd_escape_multiball_play_start_super_jackpot_sound:
    super_jackpot_is_lit_score_v1:
      volume: 1.0
  cmd_escape_play_super_jackpot_hit_sound:
    escape_mb_super_jackpot_v1_score:
      volume: 1.0
  cmd_escape_multiball_play_jerry_callout{current_player.v_escape_shoot_captive_ball_vo_fired==1}:
    escape_multiball_jerry_callout:
      volume: 1.0
  cmd_escape_multiball_play_pam_callout{current_player.v_escape_shoot_captive_ball_vo_fired==1}:
    escape_multiball_pam_callout:
      volume: 1.0
  cmd_escape_multiball_play_kirk_callout{current_player.v_escape_shoot_captive_ball_vo_fired==1}:
    escape_multiball_kirk_callout:
      volume: 1.0
  cmd_escape_multiball_play_franklin_callout{current_player.v_escape_shoot_captive_ball_vo_fired==1}:
    escape_multiball_franklin_callout:
      volume: 1.0
  cmd_escape_multiball_play_sally_callout{current_player.v_escape_shoot_captive_ball_vo_fired==1}:
    escape_multiball_sally_callout:
      volume: 1.0
