#config_version=5

mode:
  start_events:
    - cmd_start_mode_standard_extra_ball
  stop_events:
    - cmd_stop_mode_standard_extra_ball
  priority: 1000

event_player:
  mode_standard_extra_ball_started{current_player.v_lit_extra_balls>0}:
    - cmd_turn_on_extra_ball_light
  player_v_lit_extra_balls{value>0}:
    - cmd_turn_on_extra_ball_light
    - cmd_play_light_extra_ball_audio
  s_captive_ball_target_active{current_player.v_lit_extra_balls>0}:
    - cmd_score_extra_ball
    - cmd_set_extra_ball_animation_playing
    - cmd_award_extra_ball
    - cmd_play_extra_ball_award_show
    - cmd_play_extra_ball_show_audio
    - cmd_unlight_extra_ball
    - cmd_turn_off_extra_ball_light
  ball_started{is_extra_ball}:
    - cmd_play_shoot_again_show
  cmd_super_skill_shot_award_extra_ball:
    - cmd_light_extra_ball

variable_player:
  cmd_light_extra_ball:
    v_lit_extra_balls: 1
  cmd_unlight_extra_ball:
    v_lit_extra_balls:
      int: 0
      action: set
  cmd_award_extra_ball:
    extra_balls: current_player.v_lit_extra_balls
  cmd_set_extra_ball_animation_playing:
    v_extra_ball_animation_playing:
      int: 1
      action: set
  mode_standard_extra_ball_started:
    v_extra_ball_animation_playing:
      int: 0
      action: set
  slide_extra_ball_award_slide_1_removed:
    v_extra_ball_animation_playing:
      int: 0
      action: set

sound_player:
  cmd_play_extra_ball_show_audio: extra_ball_award
  cmd_play_light_extra_ball_audio: extra_ball_lit_sound
  cmd_play_shoot_again_show: shoot_again_sound

show_player:
  cmd_turn_on_extra_ball_light:
    on:
      show_tokens:
        lights: super_jackpot
  cmd_turn_off_extra_ball_light:
    off:
      show_tokens:
        lights: super_jackpot
  cmd_play_light_extra_ball_show:
    light_extra_ball_show:
      action: play
      loops: 0
      priority: 1000
  cmd_play_extra_ball_award_show:
    award_extra_ball_show:
      action: play
      loops: 0
  cmd_play_shoot_again_show:
    shoot_again_show:
      action: play
      loops: 0
