#config_version=5

images:
  leatherface:
    file: leatherface.gif
  chainsaw_multiball_start:
    file: chainsaw_multiball_v4.gif
  space_jam_take_over_start:
    file: space_jam_takeover_3.gif
  chainsaw_multiball_jackpot:
    file: cs_jackpot_v1.gif
  chainsaw_multiball_super_jackpot:
    file: cs_super_jackpot_v1.gif
  chainsaw_multiball_space_jam_takeover_jackpot:
    file: sj_jackpot_v1.gif
  saved_from_the_grave:
    file: save_from_the_grave_v3noball.png
  saved_from_the_grave_ball:
    file: save_from_the_grave_v3ball.png
  extra_ball_award:
    file: extra_ball_v3.gif
  extra_ball_lit:
    file: extra_ball_is_lit_v3.gif
  shoot_again:
    file: shoot_again_v1.gif
  help:
    file: help_v2.gif
