#config_version=5

modes:
  - base
  - bonus
  - chainsaw
  - escape
  - escape_multiball
  - franklin
  - franklin_frenzy
  - franklin_hurry_up
  - help
    #  - test
  - mask
  - meathook
  - pop_bumpers
  - save_from_the_grave
  - skill_shot
  - standard_extra_ball
  - hitchhiker
  - barbecue
  - placeholder_c
  - placeholder_d
  - placeholder_e
  - placeholder_f
