#config_version=5

event_player:

  ##################################################
  # Ball Starting
  ##################################################

  ball_starting:
    - cmd_start_mode_base
    - cmd_start_modes
    - cmd_start_mode_chainsaw
    - cmd_start_mode_escape
      #    - cmd_start_mode_test
    - cmd_start_mode_franklin
    - cmd_start_mode_help
    - cmd_start_mode_mask
    - cmd_start_mode_pop_bumpers
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_skill_shot
    - cmd_start_mode_standard_extra_ball

  ball_ending:
    - cmd_clean_up_modes

  ##################################################
  # Skill Shot
  ##################################################

  cmd_skill_shot_complete:
    - cmd_stop_mode_skill_shot
    - cmd_start_mode_meathook

  ball_save_player_start_saving_ball:
    - cmd_stop_mode_skill_shot

  ##################################################
  # Chainsaw Multiball
  ##################################################

  # We need mystery meat in it's own mode
  cmd_chainsaw_multi_ball_triggered:
    - cmd_stop_mode_escape
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy # It would be awesome to have this roll over until after multiball
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers

  multiball_mb_chainsaw_multiball_ended:
    - cmd_start_mode_escape
    - cmd_start_mode_franklin
    - cmd_start_mode_mask
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_meathook
    - cmd_start_mode_pop_bumpers
    - cmd_enable_mode_switcher_and_message

  ##################################################
  # Escape Multiball
  ##################################################

  cmd_start_escape_multiball_mode:
    - cmd_stop_mode_escape
    - cmd_stop_mode_chainsaw
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy # It would be awesome to have this roll over until after multiball
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers
    - cmd_start_mode_escape_multiball

  cmd_stop_escape_multiball_mode:
    - cmd_stop_mode_escape_multiball
    - cmd_start_mode_chainsaw
    - cmd_start_mode_franklin
    - cmd_start_mode_mask
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_meathook
    - cmd_start_mode_pop_bumpers
    - cmd_start_mode_escape
    - cmd_enable_mode_switcher_and_message

  ##################################################
  # Barbecue
  ##################################################

  cmd_start_barbecue_mode:
    - cmd_stop_mode_escape
    - cmd_stop_mode_chainsaw
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy # It would be awesome to have this roll over until after multiball
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers
    - cmd_start_mode_barbecue

  cmd_stop_barbecue_mode:
    - cmd_stop_mode_barbecue
    - cmd_start_mode_chainsaw
    - cmd_start_mode_franklin
    - cmd_start_mode_mask
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_meathook
    - cmd_start_mode_pop_bumpers
    - cmd_start_mode_escape
    - cmd_enable_mode_switcher_and_message

  ##################################################
  # Hitchhiker
  ##################################################

  cmd_start_hitchhiker_mode:
    - cmd_stop_mode_escape
    - cmd_stop_mode_chainsaw
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy # It would be awesome to have this roll over until after multiball
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers
    - cmd_start_mode_hitchhiker

  cmd_stop_hitchhiker_mode:
    - cmd_stop_mode_hitchhiker
    - cmd_start_mode_chainsaw
    - cmd_start_mode_franklin
    - cmd_start_mode_mask
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_meathook
    - cmd_start_mode_pop_bumpers
    - cmd_start_mode_escape
    - cmd_enable_mode_switcher_and_message

  ##################################################
  # Grandpa
  ##################################################

  cmd_start_grandpa_mode:
    - cmd_stop_mode_escape
    - cmd_stop_mode_chainsaw
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy # It would be awesome to have this roll over until after multiball
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers
    - cmd_start_mode_grandpa

  cmd_stop_grandpa_mode:
    - cmd_stop_mode_grandpa
    - cmd_start_mode_chainsaw
    - cmd_start_mode_franklin
    - cmd_start_mode_mask
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_meathook
    - cmd_start_mode_pop_bumpers
    - cmd_start_mode_escape
    - cmd_enable_mode_switcher_and_message

  ##################################################
  # Grave
  ##################################################

  cmd_start_grave_mode:
    - cmd_stop_mode_escape
    - cmd_stop_mode_chainsaw
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers
    - cmd_start_mode_grave

  cmd_stop_grave_mode:
    - cmd_stop_mode_grave
    - cmd_start_mode_chainsaw
    - cmd_start_mode_franklin
    - cmd_start_mode_mask
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_meathook
    - cmd_start_mode_pop_bumpers
    - cmd_start_mode_escape
    - cmd_enable_mode_switcher_and_message

  ##################################################
  # Sally
  ##################################################

  cmd_start_sally_mode:
    - cmd_stop_mode_escape
    - cmd_stop_mode_chainsaw
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy # It would be awesome to have this roll over until after multiball
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers
    - cmd_start_mode_sally

  cmd_stop_sally_mode:
    cmd_stop_mode_sally:
    cmd_start_mode_chainsaw:
    cmd_start_mode_franklin:
    cmd_start_mode_mask:
    cmd_start_mode_tt_playfield:
    cmd_start_mode_meathook:
    cmd_start_mode_pop_bumpers:
    cmd_start_mode_escape:
    cmd_enable_mode_switcher_and_message:
    cmd_custom_magna_vuk_remove_event:
      post: cmd_sally_final_shot
      wait_for: slide_sally_complete_slide_removed
      priority: 1000
      mode: sally
      coil_direction: left

  ##################################################
  # Saw Em All
  ##################################################

  cmd_start_sawemall_mode:
    - cmd_stop_mode_escape
    - cmd_stop_mode_chainsaw
    - cmd_stop_mode_franklin
    - cmd_stop_mode_franklin_hurry_up
    - cmd_stop_mode_franklin_frenzy # It would be awesome to have this roll over until after multiball
    - cmd_stop_mode_mask
    - cmd_stop_mode_tt_playfield
    - cmd_stop_mode_meathook
    - cmd_stop_mode_pop_bumpers
    - cmd_start_mode_sawemall

  cmd_stop_sawemall_mode:
    - cmd_stop_mode_sawemall
    - cmd_start_mode_chainsaw
    - cmd_start_mode_franklin
    - cmd_start_mode_mask
    - cmd_start_mode_tt_playfield
    - cmd_start_mode_meathook
    - cmd_start_mode_pop_bumpers
    - cmd_start_mode_escape
    - cmd_enable_mode_switcher_and_message


  ##################################################
  # Franklin
  ##################################################

  cmd_start_franklin_hurry_up:
    - cmd_start_mode_franklin_hurry_up

  timer_franklin_hurry_up_timer_complete:
    - cmd_stop_mode_franklin_hurry_up

  timer_franklin_hurry_up_collected_timer_complete:
    - cmd_stop_mode_franklin_hurry_up

  cmd_start_franklin_frenzy:
    - cmd_start_mode_franklin_frenzy

  timer_franklin_frenzy_timer_complete:
    - cmd_stop_mode_franklin_frenzy

  ##################################################
  # Testing
  ##################################################

      #  s_left_flipper_active:
      #    cmd_stop_mode_escape
      #  s_right_flipper_active:
      #    cmd_start_mode_escape
