#config_version=5

modes:
  - base
  - bonus
  - combos
  - chainsaw
  - escape
  - escape_multiball
  - franklin
  - franklin_frenzy
  - franklin_hurry_up
  - help
    #  - test
  - mask
  - meathook
  - pop_bumpers
#  - tt_playfield
#  - tt_playfield_base
  - skill_shot
  - standard_extra_ball
  - hitchhiker
  - barbecue
  - grandpa
  - grave
  - sally
  - sawemall
  - finalbattle
  - tilt
  - pf_multi
