#config_version=5

widget_styles:
  active_left_letter_style:
    anchor_x: left
    anchor_y: bottom
    x: -126
    y: 0
    z: 2
  active_right_letter_style:
    anchor_x: left
    anchor_y: bottom
    x: 130
    y: 0
    z: 2
  collected_letter_style:
    anchor_x: left
    anchor_y: bottom
    x: 2
    y: 0
    z: 2
    opacity: 0
  chainsaw_background_letter_style:
    anchor_x: left
    anchor_y: bottom
    x: 0
    y: 0
    z: 10
  chainsaw_active_letter_style:
    anchor_x: left
    anchor_y: bottom
    x: 0
    y: 0
    z: 20
  bonus_bottom_style:
    anchor_y: botton
    y: 2
    font_name: pinball_score_v2
    font_size: 22
    number_grouping: true
    round_anchor_x: left

