#config_version=5

mode:
  start_events:
    - cmd_start_mode_placeholder_c
  stop_events:
    - cmd_stop_mode_placeholder_c
  priority: 10000

timers:
  placeholder_c_timer:
    start_value: 0
    end_value: 5
    tick_interval: 1s
    direction: up
    start_running: True

slides:
  placeholder_c_slide:
    widgets:
      - type: text
        text: PLACEHOLDER B
        style: small

slide_player:
  mode_placeholder_c_started:
    placeholder_c_slide:
      priority: 300
      expire: 5

event_player:
  mode_placeholder_c_started: cmd_release_all_bh_mode_van
  timer_placeholder_c_timer_complete: cmd_stop_placeholder_c_mode
