#config_version=5

mode:
  start_events:
    - cmd_start_mode_sawemall
  stop_events:
    - cmd_stop_mode_sawemall
  priority: 10000

##################################################
# Event Player
##################################################

event_player:

  ################################
  # MODE PROGRESSION
  ################################

  mode_sawemall_started:
    cmd_mode_intro_started:
    cmd_disable_bh_mode_van:
    cmd_sawemall_set_state_starting:
    cmd_sawemall_reset_variables:
    cmd_sawemall_start_intro_slide:
    cmd_sawemall_start_intro_slide_sound:

  slide_sawemall_intro_slide_removed:
    cmd_mode_intro_complete:
    cmd_sawemall_after_intro_complete:
    cmd_play_sawemall_music:

  cmd_sawemall_set_up_targets_phase:
    cmd_disable_bh_mode_van:
    cmd_sawemall_set_state_targets:
    cmd_show_chainsaw_idle_slide:
    cmd_eject_van_vuk_with_audio:
    cmd_sawemall_refresh_lights:
    cmd_start_rotation_timer:

  cmd_start_rotation_timer{current_player.v_sawemall_round==4}:
    cmd_start_light_swap_timer:

  player_v_sawemall_light_swap_timer_counter{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4}:
    cmd_sawemall_refresh_lights:

  cmd_show_chainsaw_idle_slide{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_start_chainsaw_idle_slide_1:

  cmd_show_chainsaw_idle_slide{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==2}:
    cmd_sawemall_start_chainsaw_idle_slide_2:

  cmd_show_chainsaw_idle_slide{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==3}:
    cmd_sawemall_start_chainsaw_idle_slide_3:

  cmd_show_chainsaw_idle_slide{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4}:
    cmd_sawemall_start_chainsaw_idle_slide_4:

  cmd_sawemall_set_up_van_phase:
    cmd_sawemall_score_targets:
    cmd_sawemall_set_state_van:
    cmd_enable_bh_mode_van:
    cmd_sawemall_refresh_lights:
    cmd_sawemall_play_running_chainsaw:
    cmd_sawemall_start_chainsaw_running_slide:
    cmd_stop_rotation_timer:

  cmd_stop_rotation_timer{current_player.v_sawemall_round==4}:
    cmd_stop_light_swap_timer:

  cmd_sawemall_after_intro_complete:
    cmd_start_sawemall_timer:
    cmd_sawemall_set_round_1:
    cmd_sawemall_set_up_targets_phase:

  cmd_sawemall_target_hit:
    cmd_sawemall_set_up_van_phase:

  ball_hold_bh_mode_van_full{current_player.v_sawemall_state=="van" and current_player.v_sawemall_round==1}:
    cmd_sawemall_score_van_1:
    cmd_pause_sawemall_timer:
    cmd_sawemall_stop_running_chainsaw:
    cmd_sawemall_start_person_chop_1:
    cmd_sawemall_play_person_chop_1_audio:

  slide_sawemall_person_chop_slide_1_removed:
    cmd_start_sawemall_timer:
    cmd_sawemall_set_round_2:
    cmd_sawemall_set_up_targets_phase:

  ball_hold_bh_mode_van_full{current_player.v_sawemall_state=="van" and current_player.v_sawemall_round==2}:
    cmd_sawemall_score_van_2:
    cmd_pause_sawemall_timer:
    cmd_sawemall_stop_running_chainsaw:
    cmd_sawemall_start_person_chop_2:
    cmd_sawemall_play_person_chop_2_audio:

  slide_sawemall_person_chop_slide_2_removed:
    cmd_start_sawemall_timer:
    cmd_sawemall_set_round_3:
    cmd_sawemall_set_up_targets_phase:

  ball_hold_bh_mode_van_full{current_player.v_sawemall_state=="van" and current_player.v_sawemall_round==3}:
    cmd_sawemall_score_van_3:
    cmd_pause_sawemall_timer:
    cmd_sawemall_stop_running_chainsaw:
    cmd_sawemall_start_person_chop_3:
    cmd_sawemall_play_person_chop_3_audio:

  slide_sawemall_person_chop_slide_3_removed:
    cmd_start_sawemall_timer:
    cmd_sawemall_set_round_4:
    cmd_sawemall_set_up_targets_phase:

  ball_hold_bh_mode_van_full{current_player.v_sawemall_state=="van" and current_player.v_sawemall_round==4}:
    cmd_sawemall_score_van_4:
    cmd_pause_sawemall_timer:
    cmd_sawemall_stop_running_chainsaw:
    cmd_sawemall_start_person_chop_4:
    cmd_sawemall_play_person_chop_4_audio:

  slide_sawemall_person_chop_slide_4_removed:
    cmd_eject_van_vuk_with_audio:
    cmd_stop_sawemall_mode:

  timer_sawemall_timer_complete:
    cmd_stop_sawemall_mode:

  ################################
  # LIGHTS
  ################################

  cmd_sawemall_refresh_lights:
    cmd_sawemall_clear_playfield_lights:
    cmd_sawemall_turn_on_playfield_lights:

  cmd_sawemall_turn_on_playfield_lights{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_flash_chainsaw:

  cmd_sawemall_turn_on_playfield_lights{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==2}:
    cmd_sawemall_flash_chain:

  cmd_sawemall_turn_on_playfield_lights{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==3}:
    cmd_sawemall_flash_saw:

  cmd_sawemall_turn_on_playfield_lights{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_light_swap_timer_counter==0 and current_player.v_sawemall_round==4}:
    cmd_sawemall_flash_chain:

  cmd_sawemall_turn_on_playfield_lights{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_light_swap_timer_counter!=0 and current_player.v_sawemall_round==4}:
    cmd_sawemall_flash_saw:

  cmd_sawemall_turn_on_playfield_lights{current_player.v_sawemall_state=="van"}:
    cmd_sawemall_flash_van:

  ################################
  # TARGETS
  ################################

  s_chain_target_c_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:
  s_chain_target_h_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:
  s_chain_target_a_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:
  s_chain_target_i_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:
  s_chain_target_n_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:

  s_saw_target_s_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:
  s_saw_target_a_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:
  s_saw_target_w_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==1}:
    cmd_sawemall_target_hit:

  s_chain_target_c_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==2}:
    cmd_sawemall_target_hit:
  s_chain_target_h_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==2}:
    cmd_sawemall_target_hit:
  s_chain_target_a_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==2}:
    cmd_sawemall_target_hit:
  s_chain_target_i_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==2}:
    cmd_sawemall_target_hit:
  s_chain_target_n_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==2}:
    cmd_sawemall_target_hit:

  s_saw_target_s_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==3}:
    cmd_sawemall_target_hit:
  s_saw_target_a_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==3}:
    cmd_sawemall_target_hit:
  s_saw_target_w_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==3}:
    cmd_sawemall_target_hit:

  s_chain_target_c_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter==0}:
    cmd_sawemall_target_hit:
  s_chain_target_h_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter==0}:
    cmd_sawemall_target_hit:
  s_chain_target_a_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter==0}:
    cmd_sawemall_target_hit:
  s_chain_target_i_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter==0}:
    cmd_sawemall_target_hit:
  s_chain_target_n_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter==0}:
    cmd_sawemall_target_hit:

  s_saw_target_s_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter!=0}:
    cmd_sawemall_target_hit:
  s_saw_target_a_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter!=0}:
    cmd_sawemall_target_hit:
  s_saw_target_w_active{current_player.v_sawemall_state=="targets" and current_player.v_sawemall_round==4 and current_player.v_sawemall_light_swap_timer_counter!=0}:
    cmd_sawemall_target_hit:

##################################################
# Timer
##################################################

timers:
  sawemall_timer:
    start_value: 70
    end_value: 0
    tick_interval: 1s
    direction: down
    control_events:
      - action: pause
        event: cmd_pause_sawemall_timer
      - action: start
        event: cmd_start_sawemall_timer

  sawemall_light_swap_timer:
    start_value: 0
    end_value: 2
    tick_interval: 2s
    direction: up
    start_running: False
    restart_on_complete: True
    control_events:
      - action: start
        event: cmd_start_light_swap_timer
      - action: stop
        event: cmd_stop_light_swap_timer

##################################################
# Variables
##################################################

variable_player:
  cmd_sawemall_reset_variables:
    v_sawemall_round:
      action: set
      string: 1

    v_sawemall_timer_counter:
      action: set
      int: 100

    v_sawemall_light_swap_timer_counter:
      action: set
      int: 0

  cmd_sawemall_set_state_starting:
    v_sawemall_state:
      action: set
      string: "starting"

  cmd_sawemall_set_state_targets:
    v_sawemall_state:
      action: set
      string: "targets"

  cmd_sawemall_set_state_van:
    v_sawemall_state:
      action: set
      string: "van"

  cmd_sawemall_set_round_1:
    v_sawemall_round:
      action: set
      int: 1

  cmd_sawemall_set_round_2:
    v_sawemall_round:
      action: set
      int: 2

  cmd_sawemall_set_round_3:
    v_sawemall_round:
      action: set
      int: 3

  cmd_sawemall_set_round_4:
    v_sawemall_round:
      action: set
      int: 4

  timer_sawemall_timer_tick:
    v_sawemall_timer_counter:
      int: device.timers.sawemall_timer.ticks
      action: set

  timer_sawemall_light_swap_timer_tick:
    v_sawemall_light_swap_timer_counter:
      int: device.timers.sawemall_light_swap_timer.ticks
      action: set

##################################################
# Slides
##################################################

slides:
  sawemall_intro_slide:
    widgets:
      - type: image
        image: saw_em_all_intro_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sawemall_chainsaw_idle_slide_1:
    widgets:
      - type: text
        text: (player|v_sawemall_timer_counter)
        style: small
        anchor_x: right
        anchor_y: top
        x: 125
        y: 31
      - type: text
        text: SHOOT THE
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 19
      - type: text
        text: CHAINSAW TARGETS
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 13
      - type: image
        image: chainsaw_still
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sawemall_chainsaw_idle_slide_2:
    widgets:
      - type: text
        text: (player|v_sawemall_timer_counter)
        style: small
        anchor_x: right
        anchor_y: top
        x: 125
        y: 31
      - type: text
        text: SHOOT THE
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 19
      - type: text
        text: CHAIN TARGETS
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 13
      - type: image
        image: chainsaw_still
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sawemall_chainsaw_idle_slide_3:
    widgets:
      - type: text
        text: (player|v_sawemall_timer_counter)
        style: small
        anchor_x: right
        anchor_y: top
        x: 125
        y: 31
      - type: text
        text: SHOOT THE
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 19
      - type: text
        text: SAW TARGETS
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 13
      - type: image
        image: chainsaw_still
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sawemall_chainsaw_idle_slide_4:
    widgets:
      - type: text
        text: (player|v_sawemall_timer_counter)
        style: small
        anchor_x: right
        anchor_y: top
        x: 125
        y: 31
      - type: text
        text: SHOOT THE
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 19
      - type: text
        text: CHAINSAW TARGETS
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 13
      - type: image
        image: chainsaw_still
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sawemall_chainsaw_running_slide:
    widgets:
      - type: text
        text: (player|v_sawemall_timer_counter)
        style: small
        anchor_x: right
        anchor_y: top
        x: 125
        y: 31
      - type: text
        text: SHOOT THE
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 18
      - type: text
        text: VAN
        style: small
        color: black
        anchor_x: center
        anchor_y: top
        round_anchor_x: left
        x: 79
        y: 12
      - type: image
        image: chainsaw_running_v1
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0

  sawemall_person_chop_slide_1:
    widgets:
      - type: image
        image: karen_v3

  sawemall_person_chop_slide_2:
    widgets:
      - type: image
        image: douchebag_v1

  sawemall_person_chop_slide_3:
    widgets:
      - type: image
        image: dumbass_v1

  sawemall_person_chop_slide_4:
    widgets:
      - type: image
        image: boss_v2

slide_player:
  cmd_sawemall_start_intro_slide:
    sawemall_intro_slide:
      priority: 500
      expire: 4.8s

  cmd_sawemall_start_chainsaw_idle_slide_1:
    sawemall_chainsaw_idle_slide_1:
      priority: 500

  cmd_sawemall_start_chainsaw_idle_slide_2:
    sawemall_chainsaw_idle_slide_2:
      priority: 500

  cmd_sawemall_start_chainsaw_idle_slide_3:
    sawemall_chainsaw_idle_slide_3:
      priority: 500

  cmd_sawemall_start_chainsaw_idle_slide_4:
    sawemall_chainsaw_idle_slide_4:
      priority: 500

  cmd_sawemall_start_chainsaw_running_slide:
    sawemall_chainsaw_running_slide:
      priority: 500

  cmd_sawemall_start_person_chop_1:
    sawemall_person_chop_slide_1:
      priority: 500
      expire: 6.4s

  cmd_sawemall_start_person_chop_2:
    sawemall_person_chop_slide_2:
      priority: 500
      expire: 7s

  cmd_sawemall_start_person_chop_3:
    sawemall_person_chop_slide_3:
      priority: 500
      expire: 8.7s

  cmd_sawemall_start_person_chop_4:
    sawemall_person_chop_slide_4:
      priority: 500
      expire: 8.7s

##################################################
# Sound
##################################################

sound_player:
  cmd_sawemall_start_intro_slide_sound:
    saw_em_all_intro_score_v1:
      action: play
      loops: 0

  cmd_play_sawemall_music:
    saw_em_all_music_v1:
      action: play
      loops: -1

  cmd_stop_sawemall_music:
    saw_em_all_music_v1:
      action: stop

  cmd_sawemall_play_person_chop_1_audio:
    saw_em_all_karen_audio_v1:
      action: play
      loops: 0

  cmd_sawemall_play_person_chop_2_audio:
    saw_em_all_douchebag_audio_v1:
      action: play
      loops: 0

  cmd_sawemall_play_person_chop_3_audio:
    saw_em_all_dumbass_audio_v1:
      action: play
      loops: 0

  cmd_sawemall_play_person_chop_4_audio:
    saw_em_all_boss_audio_v2:
      action: play
      loops: 0

  cmd_sawemall_play_running_chainsaw:
    saw_em_all_chainsaw_running_audio_v1:
      action: play
      loops: -1 
      volume: 0.2

  cmd_sawemall_stop_running_chainsaw:
    saw_em_all_chainsaw_running_audio_v1:
      action: stop

##################################################
# Shows
##################################################

show_player:
  cmd_sawemall_clear_playfield_lights:
    med_flash:
      action: stop
      show_tokens:
        lights:
          - van
          - chain_target_c
          - chain_target_h
          - chain_target_a
          - chain_target_i
          - chain_target_n
          - saw_target_s
          - saw_target_a
          - saw_target_w

  cmd_sawemall_flash_chainsaw:
    med_flash:
      action: play
      show_tokens:
        lights:
          chain_target_c,
          chain_target_h,
          chain_target_a,
          chain_target_i,
          chain_target_n,
          saw_target_s,
          saw_target_a,
          saw_target_w

  cmd_sawemall_flash_chain:
    med_flash:
      action: play
      show_tokens:
        lights:
          chain_target_c,
          chain_target_h,
          chain_target_a,
          chain_target_i,
          chain_target_n

  cmd_sawemall_flash_saw:
    med_flash:
      action: play
      show_tokens:
        lights:
          saw_target_s,
          saw_target_a,
          saw_target_w

  cmd_sawemall_flash_van:
    med_flash:
      action: play
      show_tokens:
        lights:
          van

